server:
  port: 8000


spring:
  application:
    name: cache-app
  cache:
    type: redis
    redis:
      cache-null-values: true
      time-to-live: 10ms
  data:
    redis:
      port: 6379
      host: 127.0.0.1

